M48
; DRILL file {KiCad 8.0.2} date 2024-05-19T21:43:43+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-19T21:43:43+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.2463Y-4.8575
X2.2463Y-5.085
T2
X2.1646Y-2.5835
X2.1657Y-5.9665
X4.4492Y-5.9626
X4.4496Y-2.576
M30
